;;; structure formula - generated by the Projekt 2 GUI
(structure-formula

  (seed 3)
  (variant-duration 30.0)
  (octave-division 12)

  (dynamics (ppp pp p mf f ff fff))
  (dynamics-table
    (0 1 2 3 4 5 6)
    (2 3 4)
    (0 6))

  (performance (normal muted overtone1 pizzicato bowing))
  (performance-table
    (0 1 2 3 4)
    (0 1 2)
    (0))

  (number-of-instrument-groups 2)
  (instruments
    (instrument guitar1
      (chordsize 6 6)
      (performance (normal muted overtone1))
      (dynamics (p mf f ppp))
      (compass (1 01) (5 12))
      (durations 0.1 4.0))

    (instrument guitar2
      (chordsize 1 6)
      (performance (normal muted overtone1))
      (dynamics (p mf f ff))
      (compass (1 01) (5 12))
      (durations 0.1 4.0))

    (instrument piano
      (chordsize 1 10)
      (performance (normal pizzicato))
      (dynamics (ppp pp p mf f ff fff))
      (compass (1 01) (5 12))
      (durations 0.1 4.0))

    (instrument basedrum
      (chordsize 1 1)
      (performance (normal bowing))
      (dynamics (ppp pp p mf f ff fff))
      (compass percussion)
      (durations 0.1 4.0))

    (instrument marimba
      (chordsize 1 4)
      (performance (normal bowing))
      (dynamics (mf f ff fff))
      (compass (1 01) (5 12))
      (durations 0.1 4.0)))
  (instrument-table
    (0 1 2 3)
    (0)
    (2 3))

  (entrydelays (0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8))
  (entrydelay-table
    (0 1 2)
    (3 4 5)
    (0 1 2 3 4 5 6 7))

  (durations (0.1 0.2 0.3 0.5 0.8 5.0))
  (duration-table
    (0 1 2 3 4)
    (2 3 4)
    (0 1 2))

  (registers (
    (percussion)
    ((1 01) (3 12))
    ((3 01) (5 12))))
  (register-table
    (0 1 2)
    (1 2)
    (0 2))

  (harmony
    (row (1 2 3 p 5 7 9 11 12 4 6 8 10))
    (transposition none)
    (mode per-chord))

  (principles
    (instrument (ensemble series) (order series))
    (entrydelay (ensemble series) (order (ratio ((0 1) (1 3) (2 1) (3 5) (4 2) (5 1) (6 1) (7 10)))))
    (performance (ensemble (sequence 2)) (order alea) (mode per-note))
    (dynamics (ensemble series) (order series) (mode per-chord))
    (duration (ensemble series) (order series) (relation (independent per-note)))
    (register (ensemble series) (order series) (mode per-chord)))

  (hierarchy (Ins Reg Har Per Dyn Ent Dur))
  (union none)
  (density (autonomous (low 1) (high 2) (principle (group (element series) (repetition series) (repetitions 1 4)))))
)
