;;; structure formula - generated by the Projekt 2 GUI
(structure-formula

  (seed 3)
  (variant-duration 120.0)
  (n-variants 1)
  (octave-division 12)

  (dynamics (ppp pp p mf f ff fff))
  (dynamics-table
    (1 2 3 4 5 6))

  (performance (normal muted overtone1))
  (performance-table
    (0 1 2))

  (number-of-instrument-groups 1)
  (instruments
    (instrument piano
      (chordsize 1 6)
      (performance (normal muted overtone1))
      (dynamics (p mf f ppp pp ff fff))
      (pitch-range (low (octave 1) (pitch 1)) (high (octave 6) (pitch 12)))
      (durations 0.001 16.0)))
  (instrument-table
    (0))

  (entrydelays (1/8 1/7 1/6 1/5 1/4 1/3 1/2 1/1 1 2 3 4 5 6))
  (entrydelay-table
    (0 1 2 3 4 5 6 7 8 9 10 11 12 13))

  (durations (0.01 0.02 0.1 0.2 0.3 0.5 2.0))
  (duration-table
    (4 0 5 6 1 2))

  (registers (
    (pitch-range (low (octave 1) (pitch 1)) (high (octave 1) (pitch 12)))
    (pitch-range (low (octave 2) (pitch 1)) (high (octave 2) (pitch 12)))
    (pitch-range (low (octave 3) (pitch 1)) (high (octave 3) (pitch 12)))
    (pitch-range (low (octave 4) (pitch 1)) (high (octave 4) (pitch 12)))
    (pitch-range (low (octave 5) (pitch 1)) (high (octave 5) (pitch 12)))
    (pitch-range (low (octave 6) (pitch 1)) (high (octave 6) (pitch 12)))
    (pitch-range (low (octave 7) (pitch 1)) (high (octave 7) (pitch 12)))))
  (register-table
    (0 1 2 3 4 5 6))

  (rest-mode (before-sound-entry 6.0 26.0))
  (rests (2.0 3.0 4.0))
  (rest-table
    (0 1 2))

  (harmony
    (principle row)
    (row (1 6 11))
    (transposition none))

  (principles
    (instrument (ensemble (sequence 0)) (order series))
    (entrydelay (ensemble (sequence 0)) (order (tendency (section 1.0 (start 0.0 0.1) (end 0.0 1.0)) (section 1.0 (start 0.5 1.0) (end 0.0 1.0)) (section 1.0 (start 0.1 0.2) (end 0.8 1.0)))))
    (performance (ensemble (sequence 0)) (order (sequence (0 1 2))) (mode per-chord))
    (dynamics (ensemble series) (order (group (element series) (repetition series) (repetitions 1 4))) (mode per-note))
    (duration (ensemble (sequence 0)) (order (tendency (section 1.0 (start 0.0 0.1) (end 0.8 1.0)) (section 1.0 (start 0.45 0.6) (end 0.0 1.0)))) (relation (independent per-chord)))
    (register (ensemble (sequence 0)) (order (tendency (section 1.0 (start 0.1 0.1) (end 0.0 1.0)) (section 1.0 (start 0.0 1.0) (end 0.0 0.1)) (section 1.0 (start 0.9 1.0) (end 0.1 0.1)) (section 1.0 (start 1.0 0.1) (end 0.1 0.1)))) (mode per-note))
    (rest (ensemble alea) (order alea)))

  (hierarchy (Ins Reg Har Per Dyn Ent Dur))
  (union none)
  (density (autonomous (low 1) (high 1) (principle (group (element series) (repetition series) (repetitions 1 4)))))
)
