;;; structure formula - generated by the Projekt 2 GUI
;; Tendency mask on register, otherwise very simple, one instrument, simple durations.

(structure-formula

  (seed 1)
  (variant-duration 30.0)
  (n-variants 1)
  (octave-division 12)

  (dynamics (ppp pp p mf f ff fff))
  (dynamics-table
    (0 1 2 3 4 5 6)
    (2 3 4)
    (0 6))

  (performance (normal muted overtone1 pizzicato bowing))
  (performance-table
    (0 1 2 3 4)
    (0 1 2)
    (0))

  (number-of-instrument-groups 1)
  (instruments
    (instrument guitar1
      (chordsize 6 6)
      (performance (normal muted overtone1))
      (dynamics (p mf f ppp))
      (pitch-range (low (octave 1) (pitch 1)) (high (octave 5) (pitch 12)))
      (durations 0.1 4.0))

    (instrument guitar2
      (chordsize 1 6)
      (performance (normal muted overtone1))
      (dynamics (p mf f ff))
      (pitch-range (low (octave 1) (pitch 1)) (high (octave 5) (pitch 12)))
      (durations 0.1 4.0))

    (instrument piano
      (chordsize 1 10)
      (performance (normal pizzicato))
      (dynamics (ppp pp p mf f ff fff))
      (pitch-range (low (octave 1) (pitch 1)) (high (octave 5) (pitch 12)))
      (durations 0.0 16.0))

    (instrument basedrum
      (chordsize 1 1)
      (performance (normal bowing))
      (dynamics (ppp pp p mf f ff fff))
      (pitch-range percussion)
      (durations 0.1 4.0))

    (instrument marimba
      (chordsize 1 4)
      (performance (normal bowing))
      (dynamics (mf f ff fff))
      (pitch-range (low (octave 1) (pitch 1)) (high (octave 5) (pitch 12)))
      (durations 0.1 4.0)))
  (instrument-table
    (2))

  (entrydelays (0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.004 0.005 0.009))
  (entrydelay-table
    (0 1 2)
    (5)
    (0 1 2 3 4 5 6 7)
    (8 9 10 0 3))

  (durations (0.1 0.2 0.3 0.5 0.8 5.0))
  (duration-table
    (0 1 2 3 4)
    (2 3 4)
    (0 1 2))

  (registers (
    (pitch-range (low (octave 1) (pitch 1)) (high (octave 1) (pitch 12)))
    (pitch-range (low (octave 2) (pitch 1)) (high (octave 2) (pitch 12)))
    (pitch-range (low (octave 3) (pitch 1)) (high (octave 3) (pitch 12)))
    (pitch-range (low (octave 4) (pitch 1)) (high (octave 4) (pitch 12)))
    (pitch-range (low (octave 5) (pitch 1)) (high (octave 5) (pitch 12)))))
  (register-table
    (2)
    (0 1 2 3 4)
    (0 4))

  (harmony
    (principle row)
    (row (1 7 1 7 1 3 7))
    (transposition none))

  (principles
    (instrument (ensemble alea) (order (group (element series) (repetition series) (repetitions 1 3))))
    (entrydelay (ensemble (sequence 1)) (order (tendency (section 1.0 (start 0.0 1.0) (end 0.9 1.0)) (section 1.0 (start 0.0 0.1) (end 0.0 0.1)) (section 1.0 (start 1.0 1.0) (end 0.0 1.0)))))
    (performance (ensemble (sequence 2)) (order alea) (mode per-chord))
    (dynamics (ensemble series) (order series) (mode per-chord))
    (duration (ensemble series) (order series) (relation (independent per-note)))
    (register (ensemble series) (order series) (mode per-note)))

  (hierarchy (Ins Reg Per Dyn Har Ent Dur))
  (union none)
  (density (autonomous (low 1) (high 3) (principle (tendency (section 1.0 (start 0.5 0.6) (end 0.0 1.0)) (section 1.0 (start 0.9 1.0) (end 0.0 0.4))))))
)
