;;; structure formula - generated by the Projekt 2 GUI
;; Tendency mask on register, otherwise very simple, one instrument, simple durations.

(structure-formula

  (seed 3)
  (variant-duration 10)
  (n-variants 3)
  (octave-division 12)

  (dynamics (ppp pp p mf f ff fff))
  (dynamics-table
    (0 1 2 3 4 5 6)
    (2 3 4)
    (0 6))

  (performance (normal muted overtone1 pizzicato bowing))
  (performance-table
    (0 1 2 3 4)
    (0 1 2)
    (0))

  (number-of-instrument-groups 1)
  (instruments
    (instrument guitar1
      (chordsize 6 6)
      (performance (normal muted overtone1))
      (dynamics (p mf f ppp))
      (pitch-range (low (octave 1) (pitch 1)) (high (octave 5) (pitch 12)))
      (durations 0.1 4.0))

    (instrument guitar2
      (chordsize 1 6)
      (performance (normal muted overtone1))
      (dynamics (p mf f ff))
      (pitch-range (low (octave 1) (pitch 1)) (high (octave 5) (pitch 12)))
      (durations 0.1 4.0))

    (instrument piano
      (chordsize 1 10)
      (performance (normal pizzicato))
      (dynamics (ppp pp p mf f ff fff))
      (pitch-range (low (octave 1) (pitch 1)) (high (octave 5) (pitch 12)))
      (durations 0.0 16.0))

    (instrument basedrum
      (chordsize 1 1)
      (performance (normal bowing))
      (dynamics (ppp pp p mf f ff fff))
      (pitch-range percussion)
      (durations 0.1 4.0))

    (instrument marimba
      (chordsize 1 4)
      (performance (normal bowing))
      (dynamics (mf f ff fff))
      (pitch-range (low (octave 1) (pitch 1)) (high (octave 5) (pitch 12)))
      (durations 0.1 4.0)))
  (instrument-table
    (2))

  (entrydelays (0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8))
  (entrydelay-table
    (0 1 2)
    (3 4 5)
    (0 1 2 3 4 5 6 7))

  (durations (0.1 0.2 0.3 0.5 0.8 5.0))
  (duration-table
    (0 1 2 3 4)
    (2 3 4)
    (0 1 2))

  (registers (
    (pitch-range (low (octave 1) (pitch 1)) (high (octave 1) (pitch 12)))
    (pitch-range (low (octave 2) (pitch 1)) (high (octave 2) (pitch 12)))
    (pitch-range (low (octave 3) (pitch 1)) (high (octave 3) (pitch 12)))
    (pitch-range (low (octave 4) (pitch 1)) (high (octave 4) (pitch 12)))
    (pitch-range (low (octave 5) (pitch 1)) (high (octave 5) (pitch 12)))))
  (register-table
    (2)
    (0 1 2 3 4)
    (0 4))

  (harmony
    (principle interval)
    (matrix (rows (
        (1 0 0 0 0 0 1 0 0 0 0)
        (0 0 0 0 0 0 0 0 0 0 0)
        (0 0 0 0 0 0 0 0 0 0 0)
        (0 0 0 0 0 0 0 0 0 0 0)
        (0 0 0 0 0 0 0 0 0 0 0)
        (0 0 0 0 0 0 0 0 0 0 0)
        (1 0 0 0 0 0 1 0 0 0 0)
        (0 0 0 0 0 0 0 0 0 0 0)
        (0 0 0 0 0 0 0 0 0 0 0)
        (0 0 0 0 0 0 0 0 0 0 0)
        (0 0 0 0 0 0 0 0 0 0 0)
      )))
    (forbidden-tones ()))

  (principles
    (instrument (ensemble alea) (order (group (element series) (repetition series) (repetitions 1 3))))
    (entrydelay (ensemble series) (order (ratio ((0 1) (1 3) (2 1) (3 5) (4 2) (5 1) (6 1) (7 10)))))
    (performance (ensemble (sequence 2)) (order alea) (mode per-chord))
    (dynamics (ensemble series) (order series) (mode per-chord))
    (duration (ensemble series) (order series) (relation (shorter-than-entry per-note)))
    (register (ensemble series) (order series) (mode per-note)))

  (hierarchy (Ins Reg Per Dyn Har Ent Dur))
  (union none)
  (density (autonomous (low 1) (high 3) (principle (tendency (section 1.0 (start 0.5 0.6) (end 0.0 1.0)) (section 1.0 (start 0.9 1.0) (end 0.0 0.4))))))
)
